public class ClassEstudo {
        private void printText (){
            system.debug('Teste');
            system.debug('Teste Dois');
	    system.debug('Teste Tres');
            system.debug('Teste Quatro');
	    system.debug('Teste Cinco');
	    system.debug('Teste Seis');
            system.debug('Teste Sete');
			system.deubg('Teste Merge');
        }
		
		private void printTextDois (){
            system.debug('Teste');
            system.debug('Teste Dois');
			system.debug('Teste Tres');
            system.debug('Teste Quatro');
			system.debug('Teste Cinco');
			system.deubg('Teste Merge Dois');
        }
}
