public class ClassEstudo {
        private void printText (){
            system.debug('Teste');
            system.debug('Teste Dois');
			system.debug('Teste Tres');
            system.debug('Teste Quatro');
			system.debug('Desenvolvendo Funcionalidade normalmente');
			system.debug('BugFIX');
        }
		
		  private void printCorrecaoBugFix(){
            system.debug('Teste');
            system.debug('Teste Dois');
			system.debug('Teste Tres');
            system.debug('Teste Quatro');
			system.debug('Desenvolvendo Funcionalidade normalmente');
			system.debug('BugFIX');
        }
}